parameters:
#    crtx_country_iso.example.class: CRTX\CountryISOBundle\Example

services:
#    crtx_country_iso.example:
#        class: %crtx_country_iso.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
